### ISSUE TITLE
Invalid signature error

### ISSUE THREAD

**Issue by zakisaad** [aadityachakravarty/magento-api-rest#2]
Hi - 

We are encountering signature generation issues using this library. We are on the 2.3.3 M2 codebase with the latest security patch (2.3.3-p1).

Using the code snippet below, the console logs an error, specifically:

'The signature is invalid. Verify and try again.'

```
const magClient = new MagentoAPI({
  url: 'https://redacted.com',
  consumerKey: 'XXX',
  consumerSecret: 'XXX',
  accessToken: 'XXX',
  tokenSecret: 'XXX',
  // 'magentoVersion': 'V1'
});

magClient
  .get('orders', {})
  .then((response) => {
    console.log(response);
  })
  .catch((error) => {
    console.log(error);
  });
```

I have switched between SHA1, SHA256, etc to no avail. In your experience, is there anything obvious that may be causing this issue?

TIA

**Comment by aaditya** [comment]
Hey, 
The signature error normally occurs with either a malformed URL or rejected Access Token/Token Secret, SO step 1 should be checking the credentials and/or reauthorizing them from the admin panel, or in case of malformed URL, The library appends ?searchCriteria=all in case no filters are specified.
Or, try by removing the {} in the ".get" request.

**Comment by zakisaad** [comment]
Yep - switching to the development branch (which uses SHA-1), and setting a proper filter did the trick.

Thanks!
