### ISSUE TITLE
Cannot find module './lib/transform'

### ISSUE THREAD

**Issue by webdevNYC** [aadityachakravarty/magento-api-rest#4]
H there, I have installed "npm i magento-api-rest" and it didnt install the ./lib/transform folder, any guess what could be wrong?

Thank you,

**Comment by aaditya** [comment]
Sorry for the late reply, It looks like an issue with the Babel Config and the lib folder is not getting updated at npm.

**Comment by aaditya** [comment]
Hi !

Thanks for using the package, the problem was with the "files" part in package.json. It has been fixed.
