### ISSUE TITLE
failed with code 401

### ISSUE THREAD

**Issue by danj-O** [aadityachakravarty/magento-api-rest#5]
I am getting a 401 response and data message of "The signature is invalid. Verify and try again."
```
const Magento = require('magento-api-rest').default

const client = new Magento({
    'url': 'http://<sitetempurlstring>.mojostratus.io/',
    'consumerKey': '<my integration key>',
    'consumerSecret': '<my integration secret>',
    'accessToken': '<my integration token>',
    'tokenSecret': '<my integration token secret>',
});

async function getOrders () {
  try {
      let { data } = await client.get('products');
      console.log(data)
  } catch (err) {
    console.log('err', err)
  }
}
getOrders()
```

Any help would be greatly appreciated

**Comment by aaditya** [comment]
Hi , Sorry for the late reply, try changing the sha value to 256, by default the sha value used is sha1, 
`const client = new Magento({
    'url': 'http://<sitetempurlstring>.mojostratus.io/',
    'consumerKey': '<my integration key>',
    'consumerSecret': '<my integration secret>',
    'accessToken': '<my integration token>',
    'tokenSecret': '<my integration token secret>',
    'sha': 256,
});`

**Comment by aaditya** [comment]
Another reason could be that you're accessing your store over http but you have configured it over https
Or
Check the domain in your Magento Config

Hope either of those helps

**Comment by aaditya** [comment]
Also, please checkout #2

**Comment by aaditya** [comment]
Closing this thread as this seems to be inactive
