### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by pranav1812** [aadityachakravarty/magento-api-rest#8]
Hi, I'm on Magento 1.9 and I'm getting the 404 error.
Here's my request

```
const Magento = require('magento-api-rest').default;

const client = new Magento({
    'url': '<base_url>/index.php/api/rest', // tried with only <base_url> and <base_url/index.php>
    'consumerKey': '<consumer-key>',
    'consumerSecret': '<secret>',
    'accessToken': '<permanent access token>',
    'tokenSecret': '<token secret>',
});

client.get('/products', {}).then(function (result) {console.log(result)}).catch(function (error) {console.log(error.message)});
```

PS: I actually need to list all the customers, /customers is giving the same error. 
PS: 2...  I followed this tutorial `https://www.eglobeits.com/blog/how-to-access-magento-rest-and-oAuth-settings-for-rest-api/` to generate oAuth creds... Even here I get 404 in postman in last step, ie. 
```
Method: GET
Url:http://your-url.com/api/rest/products
```

PS: 3... I didn't setup magento from scratch, instead used a google marketplace installation `https://console.cloud.google.com/marketplace/product/miriinfotech-public/magento-31-january-2020?authuser=4&project=apt-cubist-307713`

Thanks

**Comment by esterified** [comment]
hey @pranav1812 how did you fix this? or did you get any explanation for the 404 error?
